/**
 * Generated by scripts/update-models-catalog.mjs.
 * Source: https://models.dev/api.json
 * Catalog hash: sha256:385c15796f23d90a17e52fbcee0b66d1b1e63da32b01e63bf9b58e32f36a3945
 * Do not edit manually.
 */
export const anthropicModelIds = [
  "claude-fable-5",
  "claude-fable-5-1",
  "claude-haiku-4-5",
  "claude-haiku-4-5-20251001",
  "claude-opus-4-5",
  "claude-opus-4-5-20251101",
  "claude-opus-4-6",
  "claude-opus-4-7",
  "claude-opus-4-8",
  "claude-opus-5",
  "claude-sonnet-4-5",
  "claude-sonnet-4-5-20250929",
  "claude-sonnet-4-6",
  "claude-sonnet-5",
] as const;

export type AnthropicModelId = (typeof anthropicModelIds)[number];
