/**
 * Generated by scripts/update-models-catalog.mjs.
 * Source: https://models.dev/api.json
 * Catalog hash: sha256:51e4f8b3e3951e60092c297993cd821daef74484058d1541132fc2c0666b7761
 * Do not edit manually.
 */
export const anthropicModelIds = [
  "claude-fable-5",
  "claude-fable-5-1",
  "claude-haiku-4-5",
  "claude-haiku-4-5-20251001",
  "claude-opus-4-5",
  "claude-opus-4-5-20251101",
  "claude-opus-4-6",
  "claude-opus-4-7",
  "claude-opus-4-8",
  "claude-opus-5",
  "claude-opus-5-5",
  "claude-sonnet-4-5",
  "claude-sonnet-4-5-20250929",
  "claude-sonnet-4-6",
  "claude-sonnet-5",
] as const;

export type AnthropicModelId = (typeof anthropicModelIds)[number];
